### ISSUE TITLE
CS Can't go online

### ISSUE THREAD

**Issue by SQLkiller** [optiv/Ivy#11]
./Ivy -Ix64 payload.vba -P Inject -sandbox -O 1 ，after execution，A file without suffix will be generated. After changing the suffix xls, it cannot go online.

**Comment by Tylous** [comment]
Pardon? I Am a little confused?

**Comment by SQLkiller** [comment]
I mean can't go online cobalt strike after opening the makefile

**Comment by ScriptIdiot** [comment]
Are you executing yours in domain joined machine?

**Comment by Tylous** [comment]
Are you saying the loaders are not working for you with cobalt strike?

**Comment by Tylous** [comment]
bumping

**Comment by SQLkiller** [comment]
I read the test command you added, but he reported an error。
`root：~/Ivy# ./Ivy -Ix64 test64.c -P Local -O SampleLocal.js


     ___   ___      ___  ___    ___ 
    |\  \ |\  \    /  /||\  \  /  /|
    \ \  \\ \  \  /  / /\ \  \/  / /
     \ \  \\ \  \/  / /  \ \    / / 
      \ \  \\ \    / /    \/  /  /  
       \ \__\\ \__/ /   __/  / /    
        \|__| \|__|/   |\___/ /     
                       \|___|/   
                       (@Tyl0us)
The suffering. The pain. Can't you hear them? 
Their cries for mercy?

2022/01/30 11:29:59 Error: Invalid delivery command option, please choose one of the acceptable options
`
It prompts Invalid delivery command option，But the command options should be fine

**Comment by Tylous** [comment]
I just pushed a small update this morning, pull the new version and let me know if it's still an issue.

**Comment by Tylous** [comment]
Closing this issue since it was addressed in a recent update and there hasn't been any update in 7 days.
