### ISSUE TITLE
Error in Windows 64 bit with 32 bit office 

### ISSUE THREAD

**Issue by ScriptIdiot** [optiv/Ivy#19]
![image](https://user-images.githubusercontent.com/21979646/153202674-a70689be-ce3c-4aa4-8eb8-712f973e8d4b.png)
As above, tried several combinations to generate but getting the same error. bin is from CS, thanks!

**Comment by Tylous** [comment]
Hello, I need more information to go on. Like what commands you ran with ivy to make the loader, the endpoint you were running on version of office?

**Comment by Tylous** [comment]
Closing due to lack of response
